name: "Data: Update base-files info"
# Triggered by data-update-partners-data.yml
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["Data: Update base-files info"]

concurrency:
  group: base-files-info
  cancel-in-progress: false

jobs:
  run-script:
    name: "Update base-files info"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      # Step 3: Install dependencies (if you have any)
      - name: Install dependencies
        run: |
          sudo apt install -y python3-requests python3-lxml
      # Step 4: Run the Python script
      - name: Run parser script
        run: |
          ./scripts/generate-base-files-info-json.py base-files
      # Step 5: Commit changes if any
      - name: Commit changes if any
        run: |
          git checkout data
          mkdir -p data/
          mv base-files.json data/base-files.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/base-files.json
          git diff --cached --quiet || git commit -m "Update base-files package info"
          git push

      - name: "Generate directory"
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: "Web: Directory listing"

