name: "Maintenance: Clean workflow logs"

on:
  schedule:
    - cron: "0 0 * * 2"  # Runs "At 00:00 on Tuesday." (see https://crontab.guru)

  workflow_dispatch:
    inputs:
      runs_older_than:
        description: "The amount of days old to delete"
        default: "21"
        required: false

env:
  SCHEDULED_RUNS_OLDER_THAN: "21"
  SCHEDULED_RUNS_TO_KEEP: "0"

jobs:
  clean-logs:
    runs-on: Linux
    if: ${{ github.repository_owner == 'Armbian' }}
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v7
        with:
          runs_older_than: ${{ github.event.inputs.runs_older_than || env.SCHEDULED_RUNS_OLDER_THAN }}
          runs_to_keep: ${{ github.event.inputs.runs_to_keep || env.SCHEDULED_RUNS_TO_KEEP }}

