name: "Infrastructure: Repository update"
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["Prepare incoming"]

env:
  STORAGE_PATH: /armbian/openssh-server/storage
  PUBLISHING_PATH: /publishing/repository
  CLEANUP_INPUT: true
  DRY_RUN_SYNC: false

concurrency:
  group: pipeline
  cancel-in-progress: false

jobs:

  Payload:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          echo "target = ${{ github.event.client_payload.target }}"
